version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    restart: always
    user: root
    ports:
      - 80:8080
    container_name: tgl-jenkins
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
