replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: IfNotPresent

kafka:
  brokerConnect: kafka-0.kafka.default.svc.cluster.local:9092, kafka-1.kafka.default.svc.cluster.local:9092, kafka-2.kafka.default.svc.cluster.local:9092
  properties: ""
  truststore: ""
  keystore: ""
  propertiesFile: "kafka.properties"
  truststoreFile: "kafka.truststore.jks"
  keystoreFile: "kafka.keystore.jks"

host:

jvm:
  opts: ""
jmx:
  port: 8686

nameOverride: ""
fullnameOverride: ""

cmdArgs: ""

server:
  port: 9000
  servlet:
    contextPath: /kafdrop

service:
  annotations: {}
  type: NodePort
  port: 9000
  nodePort: 30900

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 1m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

mountProtoDesc:
  enabled: false
  hostPath:
