apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-ozone.fullname" . }}
  labels:
    {{- include "apache-ozone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9876
      targetPort: http
      protocol: TCP
      name: http1
    - port: 9878
      targetPort: http
      protocol: TCP
      name: http2
  selector:
    {{- include "apache-ozone.selectorLabels" . | nindent 4 }}
