apiVersion: v1
kind: Service
metadata:
  name: om
spec:
  type: NodePort
  ports:
  - port: {{ .Values.serviceom.port }}
    nodePort: {{ .Values.serviceom.nodePort }}
    name: ui
  selector:
    app: ozone
    component: om
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: om
  labels:
    app.kubernetes.io/component: ozone
spec:
  selector:
    matchLabels:
      app: ozone
      component: om
  serviceName: om
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: om
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9874"
        prometheus.io/path: /prom
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: om
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - ozone
        - om
        env:
        - name: WAITFOR
          value: scm-0.scm:9876
        - name: ENSURE_OM_INITIALIZED
          value: /data/metadata/om/current/VERSION
        livenessProbe:
          tcpSocket:
            port: 9862
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: data
          mountPath: /data
      volumes: []
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
